# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AW-Matrix client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        args: install activitywatch
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.6.0
      with:
        environment-file: environment.yml
        activate-environment: aw-matrix
    - name: Test with pytest
      run: |
        pytest
